version: '2'
services:
  iotapp:
    build: ./iotapp
    image: python:3-buster
    container_name: iotapp
    ports:
      - "80:80"
    links:
      - db
  db:
    build: ./db
    image: jsurf/rpi-mariadb
    container_name: db
    hostname: db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3_Yellow_mujis
      MYSQL_DATABASE: iot
      MYSQL_USER: pi
    volumes:
      - ./db:/docker-entrypoint-initdb.d/schema.sql
